atari:
  batch_size: 32
  buffer_size: 100000
  env_wrapper:
  - stable_baselines3.common.atari_wrappers.NoopResetEnv
  - stable_baselines3.common.atari_wrappers.MaxAndSkipEnv
  - stable_baselines3.common.atari_wrappers.EpisodicLifeEnv
  - stable_baselines3.common.atari_wrappers.ClipRewardEnv
  exploration_final_eps: 0.01
  exploration_fraction: 0.1
  gradient_steps: 1
  learning_rate: 0.0001
  learning_starts: 100000
  n_timesteps: 10000000.0
  optimize_memory_usage: false
  policy: MlpPolicy
  target_update_interval: 1000
  train_freq: 4
